# Generated by Django 3.2.7 on 2021-10-18 19:46

from django.db import migrations, models
import myapp.storages


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=myapp.storages.ProtectedStorage, upload_to='prodicts/'),
        ),
    ]
