# Generated by Django 3.2.7 on 2021-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
