# Generated by Django 3.2.7 on 2021-11-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_product_requires_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='requires_shipping',
        ),
    ]
